Bluekey-Payment-System/BPS-FE

src/components/common/Dropdown/Dropdown.tsx, src/components/common/Dropdown/DropdownList.tsx, src/components/common/Dropdown/DropdownSelectedValue.tsx, src/components/common/Dropdown/DropdownUI.module.scss, src/components/common/Dropdown/DropdownUI.tsx, src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx, src/pages/tony.page.tsx
- input 기능이 추가된 드롭다운을 제작하였습니다.
- 간단한 로직 설명
- 이전에 만들었던 드롭다운과 마찬가지로 `dropdownListData={["혁기", "아이유", "볼빨간사춘기", "할아버지"]} 리스트 데이터를 넣어줍니다. 여기서 input이 있는 기능을 사용하고 싶으면 `withInput={true}`값만 넣어주시면 돼요!
- 스타일링은 미완성인 상태입니다. 리아님에게 이 컴포넌트가 어디서 사용될지 말씀드린 상태라 추후에 리아님이 제작해주시는대로 디자인을 반영해서 재수정하겠습니다!
=> BPS-48/input 기능이 추가된 드롭다운 제작

src/components/common/CommonBtns/Button/Button.tsx, src/components/common/CommonBtns/ChipButton/ChipButton.module.scss, src/components/common/CommonBtns/ChipButton/ChipButton.tsx, src/pages/ian.page.tsx
- ChipButton 컴포넌트 제작
- size: small
- size: small + disabled
- size: large
- 기본 인터페이스는 일반 Button과 동일합니다.
- ChipButton은 size: small인 경우가 대부분이라, small을 default 값으로 설정했습니다.
- 애매하거나 같이 얘기해보고 싶은 부분
=> BPS-19/ChipButton 컴포넌트 제작

src/components/common/CustomLegend/CustomLegend.module.scss, src/components/common/Dropdown/DropdownUI.module.scss, src/styles/_mixins.scss, src/utils/utilFormatMoney.ts
Ellipsis 믹스인 추가, 금액포맷 함수 수정
- Ellipsis 믹스인 추가하여 ellipsis 스타일을 적용하던 컴포넌트에 적용
- 금액포맷 함수에서 money에 null 타입의 값도 올 수 있도록 수정
=> BPS-68/Ellipsis 믹스인 추가, 금액포맷 함수 수정

public/images/page-ellipsis.svg, src/components/common/Pagination/Pagination.tsx, src/components/common/Pagination/PaginationArrowUI.module.scss, src/components/common/Pagination/PaginationArrowUI.tsx, src/components/common/Pagination/PaginationUI.module.scss, src/components/common/Pagination/PaginationUI.tsx, src/constants/pagination.tsx, src/pages/ian.page.tsx, src/utils/utilUpdateQueryParam.ts
페이지네이션 컴포넌트 제작
- 페이지네이션 컴포넌트 제작
- 페이지 이동 간 쿼리 파람을 교체하기 위한 utilUpdateQueryParam 함수 제작
- `<Pagination page={17} totalItems={120} itemsPerPage={6} />` + `14 호버`
- `<Pagination page={1} totalItems={120} itemsPerPage={6} />` + `> 화살표 호버`
- `<Pagination page={19} totalItems={120} itemsPerPage={6} />`
- 페이지 번호가 쿼리파람으로 들어올 것을 생각하여, `queryParamName을 prop`으로 설정했습니다. `기본값을 page`로 설정하여 한 페이지에 페이지네이션이 두 번 이상 쓰이는 아티스트 계정 관리 같은 페이지에서만 따로 값을 구별해서 주면 됩니다.
- 그 외엔 javadoc 참고 부탁드립니다.
=> BPS-22/페이지네이션 컴포넌트 제작

src/types/dto.ts, src/types/enums/user.enum.ts
- dto type 제작
- 이야기 하고싶은 부분은 셀프 코드리뷰 남기겠습니다!
=> BPS-102/ dto type 제작

next.config.js, src/constants/mock.ts, src/services/api/types/admin.ts, src/services/api/types/albums.ts, src/services/api/types/artist.ts, src/services/api/types/transaction.ts, src/types/dto.ts
1. Api GET Response 타입 정의
2. MOCK 데이터 제작
3. MOCK 이미지 사용을 위해 next.config remotePatterns 옵션 임시 설정
mock 데이터는 스웨거의 범주대로 나뉘어있고, 각 범주 순서대로 위치해있습니다.
API 타입 정의 파일 위치, 파일 명 등을 제 생각으로 임의로 했는데 검토 부탁드립니다.
=> BPS-113/MOCK Data 제작

src/components/common/Drawer/Drawer.module.scss, src/components/layout/GNB/GNB.tsx, src/components/layout/Layout.tsx, src/components/layout/Layout.types.ts, src/components/layout/SideNav/SideNav.module.scss, src/components/layout/SideNav/SideNav.tsx, src/constants/sidenavList.ts, src/pages/_app.page.module.scss, src/pages/_app.page.tsx, src/redux/slices/userSlice.ts, src/styles/globals.scss, yarn.lock
1. sidenav item 값을 constants 폴더로 이동
2. 로그아웃 기능 추가
3. 사이드 바 호버 시 색상 변경
4. enum 변경된 타입 적용
=> BPS-117/사이드 네브 이넘 변경

src/components/common/Chart/DoughnutChart/DoughnutChart.tsx, src/components/common/Chart/LineChart/LineChart.tsx, src/components/common/Drawer/Drawer.tsx, src/components/common/Dropdown/Dropdown.tsx
- [] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항
- 차트별 jsdoc 작성
- dropdown jsdoc 수정
- drawer jsdoc 작성
=> BPS-120/jsdoc 수정

src/constants/queryKeys.ts, src/pages/_app.page.tsx, src/pages/react-query-test.page.tsx, src/services/queries/useTest.ts
- 상단 app 페이지에 QueryClientProvider 및 기타 설정
- react query를 사용한 커스텀 훅 예시 추가 (`react-query-test` URL에서 확인하세요!)
- ReactQueryDevtool을 디폴트로 open을 해두었습니다
=> BPS-119/react query 보일러 플레이트 제작 & 샘플 추가

src/components/layout/GNB/MobileGNB.module.scss
- 모바일 GNB UI가 제대로 동작안한 문제 해결
- 황당한 실수 였습니다 하하하~
=> BPS-132/모바일 GNB 에러 수정

src/components/common/Dropdown/DropdownSelectedValue.tsx, src/components/common/Dropdown/DropdownUI.module.scss, src/components/common/Dropdown/DropdownUI.tsx, src/components/common/SearchBar/SearchBar.module.scss, src/components/common/SearchBar/SearchBar.tsx
1. border 색상 변경
2. 검색창과의 높이 통일
3. 검색창 theme 추가 withSearchBar 속성을 사용하시면 오른쪽만 border-radius가 적용됩니다.
4. 드롭다운 배경색 수정
=> BPS-136/dropdown styling 변경

src/components/auth/SignupForm/SignupForm.tsx, src/components/common/ImageUploader/ImageUploader.module.scss, src/components/common/Inputs/InputLayout.module.scss, src/pages/admin/artists/new/index.module.scss, src/pages/admin/artists/new/index.page.tsx, src/pages/admin/artists/new/index.utils.ts, src/types/artist.types.ts
- 아티스트 등록 페이지를 추가했습니다. 
- useForm훅을 사용하여 각 인풋 필드를 등록하고 validate합니다.
<caption>정상 입력</caption>
<caption>validation fail</caption>
- useForm 관련 함수들 사용하는 코드가 대부분입니다. 아직 미흡하지만 질문 환영합니다.
=> BPS-97/아티스트 등록 페이지 추가

src/components/dashboard/TrackListTable/TrackListTable.module.scss, src/components/dashboard/TrackListTable/TrackListTable.tsx, src/constants/mock.ts, src/pages/ian/test.page.tsx, src/types/dto.ts
=> BPS-165/앨범 정보 보기의 트랙 리스트 테이블 제작

src/pages/admin/dashboard/[month]/index.page.tsx, src/services/queries/useDashboardTopFiveRevenueChart.tsx, src/services/queries/useDashboardTrendsChart.ts
- 대시보드 차트에서 사용할 막대, 도넛 차트용 커스텀 훅을 만들었습니다.
=> BPS-164/dashboard chart custom hook 제작

src/components/common/Chip/Chip.module.scss, src/components/common/Chip/Chip.tsx, src/components/common/Chip/Chip.utils.ts, src/utils/formatNumberToKilo.ts
- 양수인 경우 `+` prefix 추가
- null 값인 경우 `- %`로 보이도록 수정
- 1000 단위 이상인 경우 `K` 단위 추가 (증가율/감소율이 최대 크더라도 수만 단위일 거 같아 K 단위만 추가했습니다!)
=> BPS-184/Chip 컴포넌트 UI 개선

src/components/artist/ArtistProfileImage/ArtistProfileImage.tsx, src/components/common/DefaultProfileImage/DefaultProfileImage.tsx, src/components/layout/GNB/MobileGNB.tsx, src/components/layout/GNB/PCGNB.tsx
- 기존에 기본 프로필 이미지를 설정하는 쪽에서 <Avatar> 컴포넌트를 사용했는데, 사용하는 곳이 꽤 여러 곳이어서 이를 따로 커스텀 컴포넌트로 분리했습니다.
- 확실히 공통으로 빼두니 중복 코드가 없어지네요, 피드백해준 케니 굳~👍
@SeyoungCho 케니가 작업하고 계신 프로필 수정쪽은 미적용 돼있습니다!
=> BPS-198/기본 프로필 이미지 컴포넌트 제작

.env, src/components/album/AlbumForm/AlbumForm.tsx, src/components/common/Dropdown/Dropdown.tsx, src/components/common/Dropdown/Dropdown.type.ts, src/components/common/Dropdown/Dropdown.utils.ts, src/components/common/Dropdown/DropdownList.tsx, src/components/common/Dropdown/DropdownSelectedValue.tsx, src/components/common/Dropdown/DropdownUI.module.scss, src/components/common/Dropdown/DropdownUI.tsx, src/components/common/Dropdown/DropdownWithSearchBar/DropdownListWithSearchBar.tsx, src/components/common/Dropdown/setDropdownItemValue.ts, src/utils/formatDropdownList.ts
- theme에 있는 hasSearchBar를 삭제했으며 hasSearchBar prop 만 내려주면 자동으로 css 스타일링이 바뀝니다.
- 문자열만 사용할 수 있었던 dropdownDataList를 객체 값도 받을 수 있도록 수정했습니다.
- hasSearchBar를 사용할 경우, dropdownDataList 데이터를 컴포넌트를 사용하는 페이지에서 formatDropdownList 함수를 이용하여 가공시켜야됩니다..!
=> BPS-178/드롭다운 컴포넌트 객체 타입 추가

src/components/album/AlbumDetailsInformationTooltip/AlbumDetailsInformationTooltip.tsx, src/components/common/Tooltip/Tooltip.module.scss, src/pages/_document.page.tsx, src/pages/albums/[albumId]/[month]/index.page.tsx, src/services/queries/dashboard/useDashboardAlbumInfo.ts, src/services/queries/dashboard/useDashboardAlbumTrendsChart.ts
- 앨범 상세 대시보드의 각 부분 데이터에 쿼리 훅 연결
- 멘토링 등에서 얘기했던 내용을 바탕으로 해당 페이지는 데이터를 SSR Props에서 받아오지 않았습니다.
- isLoading이 끝나고 data가 존재하지 않는 경우가 없을 것으로 생각해, 컴포넌트에 `!` 단언 연산자를 사용했습니다.
- 대시보드끼리 혹은 month를 사용하는 사람끼리 통일을 하고 가야할 부분이 좀 있는 것 같아서, 회의 안건으로 적어보려고 합니다..!
=> BPS-202/앨범 상세 대시보드 페이지 퍼블리싱

src/components/album/AlbumList/AlbumList.tsx, src/components/album/AlbumListSection/AlbumListSection.tsx, src/components/common/AlbumCard/AlbumCard.tsx, src/components/common/AlbumCard/OptionsButton.tsx
- 상세 링크 `albums/{albumId}/{이전 달}`
- 앨범 수정 링크 `admin/albums/{albumId}/edit`
=> BPS-248/앨범 카드 - 상세 링크 & 수정 링크 수정

src/components/album/AlbumTrackListTable/AlbumTrackListTable.tsx, src/constants/mock.ts, src/services/api/requests/admin/admin.get.api.ts, src/services/api/requests/admin/admin.patch.api.ts, src/services/api/requests/albums/albums.delete.api.ts, src/services/api/requests/albums/albums.patch.api.ts, src/services/api/requests/albums/albums.post.api.ts, src/services/api/requests/artist/artist.get.api.ts, src/services/api/requests/artist/artist.patch.api.ts, src/services/api/requests/artist/artist.post.api.ts, src/services/api/requests/auth/auth.delete.api.ts, src/services/api/requests/auth/auth.patch.api.ts, src/services/api/requests/auth/auth.post.api.ts, src/services/api/requests/tracks/tracks.delete.api.ts, src/services/api/requests/tracks/tracks.patch.api.ts, src/services/api/requests/tracks/tracks.post.api.ts, src/services/api/requests/transaction/transaction.delete.api.ts, src/services/api/requests/transaction/transaction.get.api.ts, src/services/api/requests/transaction/transaction.post.api.ts, src/services/api/types/admin.ts, src/services/api/types/albums.ts, src/services/api/types/artist.ts, src/services/api/types/global.ts, src/services/api/types/tracks.ts, src/services/api/types/transaction.ts, src/types/dto.ts
- POST & PATCH api 함수 제작
- form-data 형태로 request를 보내는 경우, forEach문으로 request body data로 가공하는 로직 제작
- 필요한 request / response type 제작
=> BPS-236/PATCH & POST & DELETE api 함수 제작

src/components/layout/Layout.tsx, src/components/layout/Layout.types.ts, src/components/layout/SideNav/SideNav.tsx, src/hooks/useSideNavList.ts
1. const로 선언한 sidenav의 item은 초기 실행 시 스토어의 값을 받지 못해 userId가 적용되지 않는 오류가 있었습니다. 이를 커스텀훅을 제작하여 store의 값을 받도록 오류를 수정했습니다.
=> BPS-251/sidenav custom hook 제작

src/pages/admin/artists/[month]/index.page.tsx, src/pages/admin/upload-revenue/[month].page.tsx, src/services/api/artists/artists-mock-api.ts, src/services/api/requests/admin/admin.get.api.ts, src/services/api/requests/albums/albums.get.api.ts, src/services/api/requests/artist/artist.get.api.ts, src/services/api/requests/transaction/transaction.get.api.ts, src/services/queries/dashboard/queryFns/topFiveRevenueChart.ts, src/utils/subtractMonths.ts
- 차트 유틸 함수 추가: 202306, 5가 들어오면 202302, 202306 리턴
- converYearMonthToQuery 함수 삭제
- api 함수 page - 1 적용
=> BPS-252/차트 유틸 함수 추가 및 convertYearMonthToQuery 함수 삭제

src/pages/admin/manage-accounts/index.module.scss, src/pages/admin/manage-accounts/index.page.tsx, src/services/queries/manage-accounts/useAccounts.ts
- 계정관리 api 연동
- 슈퍼 어드민만 어드민 계정 api 전달
- 페이지네이션 prefetch 구현
- 로딩 처리
=> BPS-265/계정관리 페이지 api 연동

src/components/common/ExcelFileUploader/ExcelFileUploader.tsx, src/components/common/Modals/AlertModal/AlertModal.module.scss
- 잘못된 확장자의 파일이 업로드될 때, 프론트엔드 단에서 걸러서 AlertModal을 띄우도록 했습니다.
=> BPS-261/잘못된 파일 확장자일 때 AlertModal 연결

src/components/common/Dropdown/DropdownUI.module.scss, src/components/common/Filter/Filter.module.scss, src/components/common/Filter/Filter.tsx, src/components/common/Filter/FilterForm/FilterForm.module.scss, src/components/common/Filter/FilterForm/FilterForm.tsx, src/components/common/Filter/FilterForm/MultiRangeSlider.module.scss, src/components/common/Filter/FilterForm/MultiRangeSlider.tsx, src/components/common/Filter/FilterForm/MultiRangeSlider.util.ts, src/styles/globals.scss
- 필터 기능을 위한 필터 적용 폼을 컴포넌트화 하여 퍼블리싱 했습니다. 
- 요율 슬라이더를 위한 MultiSlider라는 컴포넌트를 추가했습니다. 
- 아직 기능은 넣지 않았습니다. 기능을 추가하게 되면 필터 모달 내부에 존재하는 input값들을 추적하여 쿼리 스트링을 만들어 pathname에 붙이는 방식이 될 것 같습니다
- FilterForm은 독립된 컴포넌트로써 사용시에는 모달 안에서 렌더링하면 됩니다. 현재 사용처는 필터 버튼을 누를 때 외에는 없어 보입니다. 따라서 Filter버튼에 onClick핸들러에 FilterForm을 품은 모달을 show하는 기능을 추가해 두었습니다.
=> BPS-312/필터 모달 UI퍼블리싱

README.md
=> docs: test
